apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: nagios
  name: nagios
spec:
  replicas: 1
  selector:
    app: nagios
    deploymentconfig: nagios
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: nagios
        deploymentconfig: nagios
    spec:
      containers:
      - image: registry.cto1.paas.gsnetcloud.corp/x566339/nagios:latest
        imagePullPolicy: Always
        name: nagios
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/nagios/var
          name: nagios-volume-1
        - mountPath: /opt/nagiosgraph/etc
          name: nagios-volume-2
        - mountPath: /opt/nagiosgraph/var
          name: nagios-volume-3
        - mountPath: /var/log/apache2
          name: nagios-volume-4
        - mountPath: /opt/Custom-Nagios-Plugins
          name: nagios-volume-5
        - mountPath: /opt/nagios/etc
          name: nagios-volume-6
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nagios-volume-1
      - emptyDir: {}
        name: nagios-volume-2
      - emptyDir: {}
        name: nagios-volume-3
      - emptyDir: {}
        name: nagios-volume-4
      - emptyDir: {}
        name: nagios-volume-5
      - emptyDir: {}
        name: nagios-volume-6
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
