apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: test-devops
    app_name: test-devops
    template: javase
  name: test-devops
spec:
  replicas: 1
  selector:
    app_name: test-devops
    deploymentconfig: test-devops
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: test-devops
        app_name: test-devops
        deploymentconfig: test-devops
        template: javase
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: test-devops
        - name: ARTIFACT_URL
          value: http://nexus.pro.pandora.mx.corp/repository/maven-all/mx/com/produban/hello-world/2.7.4-SNAPSHOT/hello-world-2.7.4-20180608.152645-1.jar
        - name: PBD_URL
        - name: JAVA_OPTS_EXT
          value: -Djava.security.egd=file:/dev/./urandom
        - name: JAVA_PARAMETERS
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WILY_MOM_FQDN
        - name: WILY_MOM_PORT
          value: "5001"
        - name: TZ
          value: Europe/Madrid
        image: registry.global.paas.gsnetcloud.corp/produban/javase:1.4.12.RELEASE
        imagePullPolicy: IfNotPresent
        name: test-devops
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512M
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/metadata
          name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
