apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: javase
    app_name: keymanager
    template: javase
  name: keymanager
spec:
  replicas: 1
  selector:
    app_name: keymanager
    deploymentconfig: keymanager
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app_name: keymanager
        deploymentconfig: keymanager
        template: javase
    spec:
      containers:
      - env:
        - name: KMS_PROFILE
          value: dev
        - name: KMS_LABEL
          value: v1
        - name: KMS_SERV_CONF
          value: http://config-service:8080
        - name: APP_NAME
          value: keymanager
        - name: ARTIFACT_URL
          value: https://nexus.ci.gsnet.corp/nexus/service/local/repositories/releases/content/com/santander/serenity/security/security-srv-keymanager/2.0.2-RELEASE/security-srv-keymanager-2.0.2-RELEASE.jar
        - name: PBD_URL
        - name: JAVA_OPTS_EXT
          value: -Djava.security.egd=file:/dev/./urandom
        - name: JAVA_PARAMETERS
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WILY_MOM_FQDN
        - name: WILY_MOM_PORT
          value: "5001"
        - name: TZ
          value: America/Mexico_City
        - name: SPRING_CLOUD_CONFIG_LABEL
          value: master
        - name: spring_application_name
          value: wfpyme-keymanager
        image: registry.global.paas.gsnetcloud.corp/produban/javase:latest
        imagePullPolicy: IfNotPresent
        name: keymanager
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512M
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/metadata
          name: podinfo
        - mountPath: /etc/keyman/
          name: volume-kf03h
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - name: volume-kf03h
        secret:
          defaultMode: 420
          secretName: wfpyme-pub
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
